# Generated by Django 5.0 on 2023-12-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('cpassword', models.TextField(max_length=100)),
                ('auth', models.TextField(max_length=50)),
            ],
        ),
    ]
